AllCops:
  Include:
    - attributes/*.rb
    - docs/*.rb
    - libraries/*.rb
    - recipes/*.rb
    - spec/**/*.rb
  Exclude:
    - metadata.rb
    - files/**/*
    - vendor/**/*

inherit_from: .rubocop_todo.yml

# Team preferences different from Rubocop defaults:
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/ClassCheck:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

