AllCops:
  Include:
    - attributes/*.rb
    - docs/*.rb
    - libraries/*.rb
    - recipes/*.rb
    - spec/**/*.rb
  Exclude:
    - metadata.rb
    - files/**/*
    - vendor/**/*

# Baseline code complexity metrics - we should try and reduce these over time
Metrics/AbcSize:
  Max: 157

Metrics/ClassLength:
  Max: 132

Metrics/CyclomaticComplexity:
  Max: 31

Metrics/LineLength:
  Max: 118

Metrics/MethodLength:
  Max: 110

Metrics/PerceivedComplexity:
  Max: 32

# Team preferences different from Rubocop defaults:
Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/ClassCheck:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

